// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/messaging-go/core (interfaces: MessageProcessor)
//
// Generated by this command:
//
//	mockgen -destination=./test/mocks/mock_core.go -package=mocks -typed github.com/messaging-go/core MessageProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	core "github.com/messaging-go/core"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageProcessor is a mock of MessageProcessor interface.
type MockMessageProcessor[MessageType any] struct {
	ctrl     *gomock.Controller
	recorder *MockMessageProcessorMockRecorder[MessageType]
	isgomock struct{}
}

// MockMessageProcessorMockRecorder is the mock recorder for MockMessageProcessor.
type MockMessageProcessorMockRecorder[MessageType any] struct {
	mock *MockMessageProcessor[MessageType]
}

// NewMockMessageProcessor creates a new mock instance.
func NewMockMessageProcessor[MessageType any](ctrl *gomock.Controller) *MockMessageProcessor[MessageType] {
	mock := &MockMessageProcessor[MessageType]{ctrl: ctrl}
	mock.recorder = &MockMessageProcessorMockRecorder[MessageType]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageProcessor[MessageType]) EXPECT() *MockMessageProcessorMockRecorder[MessageType] {
	return m.recorder
}

// AddMiddleware mocks base method.
func (m *MockMessageProcessor[MessageType]) AddMiddleware(middleware core.Middleware[*MessageType]) core.MessageProcessor[MessageType] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMiddleware", middleware)
	ret0, _ := ret[0].(core.MessageProcessor[MessageType])
	return ret0
}

// AddMiddleware indicates an expected call of AddMiddleware.
func (mr *MockMessageProcessorMockRecorder[MessageType]) AddMiddleware(middleware any) *MockMessageProcessorAddMiddlewareCall[MessageType] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMiddleware", reflect.TypeOf((*MockMessageProcessor[MessageType])(nil).AddMiddleware), middleware)
	return &MockMessageProcessorAddMiddlewareCall[MessageType]{Call: call}
}

// MockMessageProcessorAddMiddlewareCall wrap *gomock.Call
type MockMessageProcessorAddMiddlewareCall[MessageType any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageProcessorAddMiddlewareCall[MessageType]) Return(arg0 core.MessageProcessor[MessageType]) *MockMessageProcessorAddMiddlewareCall[MessageType] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageProcessorAddMiddlewareCall[MessageType]) Do(f func(core.Middleware[*MessageType]) core.MessageProcessor[MessageType]) *MockMessageProcessorAddMiddlewareCall[MessageType] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageProcessorAddMiddlewareCall[MessageType]) DoAndReturn(f func(core.Middleware[*MessageType]) core.MessageProcessor[MessageType]) *MockMessageProcessorAddMiddlewareCall[MessageType] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockMessageProcessor[MessageType]) Run(processor core.Processor[MessageType]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", processor)
}

// Run indicates an expected call of Run.
func (mr *MockMessageProcessorMockRecorder[MessageType]) Run(processor any) *MockMessageProcessorRunCall[MessageType] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockMessageProcessor[MessageType])(nil).Run), processor)
	return &MockMessageProcessorRunCall[MessageType]{Call: call}
}

// MockMessageProcessorRunCall wrap *gomock.Call
type MockMessageProcessorRunCall[MessageType any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageProcessorRunCall[MessageType]) Return() *MockMessageProcessorRunCall[MessageType] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageProcessorRunCall[MessageType]) Do(f func(core.Processor[MessageType])) *MockMessageProcessorRunCall[MessageType] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageProcessorRunCall[MessageType]) DoAndReturn(f func(core.Processor[MessageType])) *MockMessageProcessorRunCall[MessageType] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockMessageProcessor[MessageType]) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockMessageProcessorMockRecorder[MessageType]) Stop() *MockMessageProcessorStopCall[MessageType] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMessageProcessor[MessageType])(nil).Stop))
	return &MockMessageProcessorStopCall[MessageType]{Call: call}
}

// MockMessageProcessorStopCall wrap *gomock.Call
type MockMessageProcessorStopCall[MessageType any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessageProcessorStopCall[MessageType]) Return() *MockMessageProcessorStopCall[MessageType] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessageProcessorStopCall[MessageType]) Do(f func()) *MockMessageProcessorStopCall[MessageType] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessageProcessorStopCall[MessageType]) DoAndReturn(f func()) *MockMessageProcessorStopCall[MessageType] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
