// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/messaging-go/core (interfaces: Middleware)
//
// Generated by this command:
//
//	mockgen -destination=./test/mocks/mock_middleware.go -package=mocks -typed github.com/messaging-go/core Middleware
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder[T]
	isgomock struct{}
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder[T any] struct {
	mock *MockMiddleware[T]
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware[T any](ctrl *gomock.Controller) *MockMiddleware[T] {
	mock := &MockMiddleware[T]{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware[T]) EXPECT() *MockMiddlewareMockRecorder[T] {
	return m.recorder
}

// Process mocks base method.
func (m *MockMiddleware[T]) Process(ctx context.Context, item T, next func(context.Context, T) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, item, next)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockMiddlewareMockRecorder[T]) Process(ctx, item, next any) *MockMiddlewareProcessCall[T] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockMiddleware[T])(nil).Process), ctx, item, next)
	return &MockMiddlewareProcessCall[T]{Call: call}
}

// MockMiddlewareProcessCall wrap *gomock.Call
type MockMiddlewareProcessCall[T any] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMiddlewareProcessCall[T]) Return(arg0 error) *MockMiddlewareProcessCall[T] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMiddlewareProcessCall[T]) Do(f func(context.Context, T, func(context.Context, T) error) error) *MockMiddlewareProcessCall[T] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMiddlewareProcessCall[T]) DoAndReturn(f func(context.Context, T, func(context.Context, T) error) error) *MockMiddlewareProcessCall[T] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
